version: '3.4'

services:
  pdfdemo:
    image: ${DOCKER_REGISTRY-}pdfdemo
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdfdemo
    hostname: pdfdemo
    ports:
      - "7004:80"